// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var fundamentalStock = FundamentalStock.FromJson(jsonString);

using System.Text.Json;

namespace EODHistoricalData.NET
{
    using EODHistoricalData.NET.BusinessObjects;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class BulkFundamentalStocks : Dictionary<int, FundamentalStock>
    {
    }
    
    public partial class BulkFundamentalStocks
    {
        public static BulkFundamentalStocks FromJson(string json)
        {
            json = json.Replace("\"0000-00-00\"", "null");
            return JsonSerializer.Deserialize<BulkFundamentalStocks>(json, EODHistoricalData.NET.ConverterFundamentalStock.Settings);
        }
    }
}
