// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var exchanges = Exchange.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    public partial class Exchange
    {
        [JsonPropertyName("Name")]
        public string Name { get; set; }
        
        [JsonPropertyName("Code")]
        public string Code { get; set; }

        [JsonPropertyName("OperatingMIC")]
        public string OperatingMIC { get; set; }
        
        [JsonPropertyName("Country")]
        public string Country { get; set; }

        [JsonPropertyName("Currency")]
        public string Currency { get; set; }
    }


    public partial class Exchange
    {
        public static List<Exchange> FromJson(string json) => JsonSerializer.Deserialize<List<Exchange>>(json, EODHistoricalData.NET.ConverterExchange.Settings);
    }

    public static class SerializeExchange
    {
        public static string ToJson(this List<Instrument> self) => JsonSerializer.Serialize(self, EODHistoricalData.NET.ConverterExchange.Settings);
    }

    internal static class ConverterExchange
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerOptions Settings = new JsonSerializerOptions
        {
            // MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            // DateParseHandling = DateParseHandling.None,
            // Converters =
            // {
            //     new NullConverter(),
            // },
            // Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            // {
            //     Errors.Add(args.ErrorContext.Error.Message);
            //     args.ErrorContext.Handled = true;
            // },
        };
    }
}
