// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var fundamentalFund = FundamentalFund.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using EODHistoricalData.NET.BusinessObjects;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    public partial class FundamentalFund
    {
        [JsonPropertyName("General")]
        public FundamentalGeneral General { get; set; }

        [JsonPropertyName("MutualFund_Data")]
        public MutualFundData MutualFundData { get; set; }
    }
    
    public partial class MutualFundData
    {
        [JsonPropertyName("Nav")]
        public decimal? Nav { get; set; }

        [JsonPropertyName("Prev_Close_Price")]
        public decimal? PrevClosePrice { get; set; }

        [JsonPropertyName("Update_Date")]
        public DateTimeOffset UpdateDate { get; set; }

        [JsonPropertyName("Portfolio_Net_Assets")]
        public decimal? PortfolioNetAssets { get; set; }

        [JsonPropertyName("Share_Class_Net_Assets")]
        public long ShareClassNetAssets { get; set; }

        [JsonPropertyName("Morning_Star_Rating")]
        public long MorningStarRating { get; set; }

        [JsonPropertyName("Morning_Star_Risk_Rating")]
        public long MorningStarRiskRating { get; set; }

        [JsonPropertyName("Morning_Star_Category")]
        public string MorningStarCategory { get; set; }

        [JsonPropertyName("Incepton_Date")]
        public DateTimeOffset? InceptonDate { get; set; }

        [JsonPropertyName("Currency")]
        public string Currency { get; set; }

        [JsonPropertyName("Domicile")]
        public string Domicile { get; set; }

        [JsonPropertyName("Yield")]
        public decimal? Yield { get; set; }

        [JsonPropertyName("Yield_YTD")]
        public decimal? YieldYtd { get; set; }

        [JsonPropertyName("Yield_1Year_YTD")]
        public decimal? Yield1YearYtd { get; set; }

        [JsonPropertyName("Yield_3Year_YTD")]
        public decimal? Yield3YearYtd { get; set; }

        [JsonPropertyName("Yield_5Year_YTD")]
        public decimal? Yield5YearYtd { get; set; }

        [JsonPropertyName("Expense_Ratio")]
        public decimal? ExpenseRatio { get; set; }

        [JsonPropertyName("Expense_Ratio_Date")]
        public DateTimeOffset? ExpenseRatioDate { get; set; }

        [JsonPropertyName("Asset_Allocation")]
        public Dictionary<string, AssetAllocation> AssetAllocation { get; set; }

        [JsonPropertyName("Value_Growth")]
        public Dictionary<string, ValueGrowth> ValueGrowth { get; set; }

        [JsonPropertyName("Top_Holdings")]
        public Dictionary<string, TopHolding> TopHoldings { get; set; }

        [JsonPropertyName("Market_Capitalization")]
        public Dictionary<string, MarketCapitalization> MarketCapitalization { get; set; }

        [JsonPropertyName("Sector_Weights")]
        public SectorWeights SectorWeights { get; set; }

        [JsonPropertyName("World_Regions")]
        public WorldRegions WorldRegions { get; set; }
    }

    public partial class AssetAllocation
    {
        [JsonPropertyName("Net_%")]
        public decimal? Net { get; set; }

        [JsonPropertyName("Long_%")]
        public decimal? Long { get; set; }

        [JsonPropertyName("Type")]
        public string Type { get; set; }

        [JsonPropertyName("Short_%")]
        public decimal? Short { get; set; }

        [JsonPropertyName("Category_Average")]
        public decimal? CategoryAverage { get; set; }

        [JsonPropertyName("Benchmark")]
        public decimal? Benchmark { get; set; }
    }

    public partial class MarketCapitalization
    {
        [JsonPropertyName("Size")]
        public string Size { get; set; }

        [JsonPropertyName("Category_Average")]
        public decimal? CategoryAverage { get; set; }

        [JsonPropertyName("Benchmark")]
        public decimal? Benchmark { get; set; }

        [JsonPropertyName("Portfolio_%")]
        public decimal? Portfolio { get; set; }
    }

    public partial class SectorWeights
    {
        [JsonPropertyName("Cyclical")]
        public Dictionary<string, Cyclical> Cyclical { get; set; }

        [JsonPropertyName("Defensive")]
        public Dictionary<string, Cyclical> Defensive { get; set; }

        [JsonPropertyName("Sensitive")]
        public Dictionary<string, Cyclical> Sensitive { get; set; }
    }

    public partial class Cyclical
    {
        [JsonPropertyName("Type")]
        public string Type { get; set; }

        [JsonPropertyName("Category_Average")]
        public decimal? CategoryAverage { get; set; }

        [JsonPropertyName("Amount_%")]
        public decimal? Amount { get; set; }

        [JsonPropertyName("Benchmark")]
        public decimal? Benchmark { get; set; }
    }

    public partial class TopHolding
    {
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonPropertyName("Owned")]
        public decimal? Owned { get; set; }

        [JsonPropertyName("Change")]
        public decimal? Change { get; set; }

        [JsonPropertyName("Weight")]
        public decimal? Weight { get; set; }
    }

    public partial class ValueGrowth
    {
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonPropertyName("Category_Average")]
        public decimal? CategoryAverage { get; set; }

        [JsonPropertyName("Benchmark")]
        public decimal? Benchmark { get; set; }

        [JsonPropertyName("Stock_Portfolio", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? StockPortfolio { get; set; }

        [JsonPropertyName("Stocks_%", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? Stocks { get; set; }
    }

    public partial class WorldRegions
    {
        [JsonPropertyName("Americas")]
        public Dictionary<string, ValueGrowth> Americas { get; set; }

        [JsonPropertyName("Greater Asia")]
        public Dictionary<string, ValueGrowth> GreaterAsia { get; set; }

        [JsonPropertyName("Greater Europe")]
        public Dictionary<string, ValueGrowth> GreaterEurope { get; set; }

        [JsonPropertyName("Market Classification")]
        public Dictionary<string, ValueGrowth> MarketClassification { get; set; }
    }

    public partial class FundamentalFund
    {
        public static FundamentalFund FromJson(string json) => JsonConvert.DeserializeObject<FundamentalFund>(json, EODHistoricalData.NET.ConverterFundamentalFund.Settings);
    }

    public static class SerializeFundamentalFund
    {
        public static string ToJson(this FundamentalFund self) => JsonConvert.SerializeObject(self, EODHistoricalData.NET.ConverterFundamentalFund.Settings);
    }

    internal static class ConverterFundamentalFund
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal },
                new NullConverter(),
            },
            Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            {
                Errors.Add(args.ErrorContext.Error.Message);
                args.ErrorContext.Handled = true;
            },
        };
    }

}
