// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EODHistoricalData.NET;
//
//    var fundamentalStock = FundamentalStock.FromJson(jsonString);

namespace EODHistoricalData.NET
{
    using EODHistoricalData.NET.BusinessObjects;
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class FundamentalStock
    {
        [JsonPropertyName("General")]
        public FundamentalGeneral General { get; set; }

        [JsonPropertyName("Highlights")]
        public Highlights Highlights { get; set; }

        [JsonPropertyName("Valuation")]
        public Valuation Valuation { get; set; }

        [JsonPropertyName("SharesStats")]
        public SharesStats SharesStats { get; set; }

        [JsonPropertyName("Technicals")]
        public FundamentalTechnicals Technicals { get; set; }

        [JsonPropertyName("SplitsDividends")]
        public SplitsDividends SplitsDividends { get; set; }

        [JsonPropertyName("outstandingShares")]
        public OutstandingShares OutstandingShares { get; set; }

        [JsonPropertyName("Earnings")]
        public Earnings Earnings { get; set; }

        [JsonPropertyName("Financials")]
        public Financials Financials { get; set; }
    }

    public partial class Earnings
    {
        [JsonPropertyName("History")]
        public Dictionary<string, History> History { get; set; }

        [JsonPropertyName("Annual")]
        public Dictionary<string, Annual> Annual { get; set; }

        [JsonPropertyName("Trend")]
        public Dictionary<string, Dictionary<string, string>> Trend { get; set; }
    }

    public partial class EarningsDetailsBase
    {
        [JsonPropertyName("date")]
        public DateTimeOffset Date { get; set; }

        [JsonPropertyName("epsActual")]
        public string EpsActual { get; set; }
    }

    public class Annual : EarningsDetailsBase
    {

    }

    public partial class History : EarningsDetailsBase
    {
        [JsonPropertyName("reportDate")]
        public DateTimeOffset? ReportDate { get; set; }

        [JsonPropertyName("epsEstimate")]
        public string EpsEstimate { get; set; }

        [JsonPropertyName("epsDifference")]
        public string EpsDifference { get; set; }

        [JsonPropertyName("surprisePercent")]
        public string SurprisePercent { get; set; }
    }

    public partial class Financials
    {
        [JsonPropertyName("Balance_Sheet")]
        public BalanceSheet BalanceSheet { get; set; }

        [JsonPropertyName("Cash_Flow")]
        public CashFlow CashFlow { get; set; }

        [JsonPropertyName("Income_Statement")]
        public IncomeStatement IncomeStatement { get; set; }
    }

    public partial class BalanceSheet
    {
        [JsonPropertyName("currency_symbol")]
        public string CurrencySymbol { get; set; }

        [JsonPropertyName("quarterly")]
        public Dictionary<string, BalanceSheetDetails> Quarterly { get; set; }

        [JsonPropertyName("yearly")]
        public Dictionary<string, BalanceSheetDetails> Yearly { get; set; }
    }

    public partial class CashFlow
    {
        [JsonPropertyName("currency_symbol")]
        public string CurrencySymbol { get; set; }

        [JsonPropertyName("quarterly")]
        public Dictionary<string, Dictionary<string, string>> Quarterly { get; set; }

        [JsonPropertyName("yearly")]
        public Dictionary<string, Dictionary<string, string>> Yearly { get; set; }
    }

    public partial class IncomeStatement
    {
        [JsonPropertyName("currency_symbol")]
        public string CurrencySymbol { get; set; }

        [JsonPropertyName("quarterly")]
        public Dictionary<string, Dictionary<string, string>> Quarterly { get; set; }

        [JsonPropertyName("yearly")]
        public Dictionary<string, Dictionary<string, string>> Yearly { get; set; }
    }

    public partial class BalanceSheetDetails
    {
        [JsonPropertyName("accountsPayable")]
        public decimal? AccountsPayable { get; set; }

        [JsonPropertyName("accumulatedAmortization")]
        public decimal? AccumulatedAmortization { get; set; }

        [JsonPropertyName("accumulatedDepreciation")]
        public decimal? AccumulatedDepreciation { get; set; }

        [JsonPropertyName("accumulatedOtherComprehensiveIncome")]
        public decimal? AccumulatedOtherComprehensiveIncome { get; set; }

        [JsonPropertyName("additionalPaidInCapital")]
        public decimal? AdditionalPaidInCapital { get; set; }

        [JsonPropertyName("capitalLeaseObligations")]
        public decimal? CapitalLeaseObligations { get; set; }

        [JsonPropertyName("capitalSurpluse")]
        public decimal? CapitalSurpluse { get; set; }

        [JsonPropertyName("cash")]
        public decimal? Cash { get; set; }

        [JsonPropertyName("cashAndShortTermInvestments")]
        public decimal? CashAndShortTermInvestments { get; set; }

        [JsonPropertyName("commonStock")]
        public decimal? CommonStock { get; set; }

        [JsonPropertyName("commonStockSharesOutstanding")]
        public decimal? CommonStockSharesOutstanding { get; set; }

        [JsonPropertyName("commonStockTotalEquity")]
        public decimal? CommonStockTotalEquity { get; set; }

        [JsonPropertyName("date")]
        public DateTime Date { get; set; }

        [JsonPropertyName("deferredLongTermAssetCharges")]
        public decimal? DeferredLongTermAssetCharges { get; set; }

        [JsonPropertyName("deferredLongTermLiab")]
        public decimal? DeferredLongTermLiab { get; set; }

        [JsonPropertyName("filing_date")]
        public DateTime? FilingDate { get; set; }

        [JsonPropertyName("goodWill")]
        public decimal? GoodWill { get; set; }

        [JsonPropertyName("intangibleAssets")]
        public decimal? IntangibleAssets { get; set; }

        [JsonPropertyName("inventory")]
        public decimal? Inventory { get; set; }

        [JsonPropertyName("liabilitiesAndStockholdersEquity")]
        public decimal? LiabilitiesAndStockholdersEquity { get; set; }

        [JsonPropertyName("longTermDebt")]
        public decimal? LongTermDebt { get; set; }

        [JsonPropertyName("longTermDebtTotal")]
        public decimal? LongTermDebtTotal { get; set; }

        [JsonPropertyName("longTermInvestments")]
        public decimal? LongTermInvestments { get; set; }

        [JsonPropertyName("negativeGoodwill")]
        public decimal? NegativeGoodwill { get; set; }

        [JsonPropertyName("netReceivables")]
        public decimal? NetReceivables { get; set; }

        [JsonPropertyName("netTangibleAssets")]
        public decimal? NetTangibleAssets { get; set; }

        [JsonPropertyName("nonCurrentAssetsTotal")]
        public decimal? NonCurrentAssetsTotal { get; set; }

        [JsonPropertyName("nonCurrentLiabilitiesOther")]
        public decimal? NonCurrentLiabilitiesOther { get; set; }

        [JsonPropertyName("nonCurrentLiabilitiesTotal")]
        public decimal? NonCurrentLiabilitiesTotal { get; set; }

        [JsonPropertyName("nonCurrrentAssetsOther")]
        public decimal? NonCurrrentAssetsOther { get; set; }

        [JsonPropertyName("noncontrollingInterestInConsolidatedEntity")]
        public decimal? NoncontrollingInterestInConsolidatedEntity { get; set; }

        [JsonPropertyName("otherAssets")]
        public decimal? OtherAssets { get; set; }

        [JsonPropertyName("otherCurrentAssets")]
        public decimal? OtherCurrentAssets { get; set; }

        [JsonPropertyName("otherCurrentLiab")]
        public decimal? OtherCurrentLiab { get; set; }

        [JsonPropertyName("otherLiab")]
        public decimal? OtherLiab { get; set; }

        [JsonPropertyName("otherStockholderEquity")]
        public decimal? OtherStockholderEquity { get; set; }

        [JsonPropertyName("preferredStockRedeemable")]
        public decimal? PreferredStockRedeemable { get; set; }

        [JsonPropertyName("preferredStockTotalEquity")]
        public decimal? PreferredStockTotalEquity { get; set; }

        [JsonPropertyName("propertyPlantAndEquipmentGross")]
        public decimal? PropertyPlantAndEquipmentGross { get; set; }

        [JsonPropertyName("propertyPlantEquipment")]
        public decimal? PropertyPlantEquipment { get; set; }

        [JsonPropertyName("retainedEarnings")]
        public decimal? RetainedEarnings { get; set; }

        [JsonPropertyName("retainedEarningsTotalEquity")]
        public decimal? RetainedEarningsTotalEquity { get; set; }

        [JsonPropertyName("shortLongTermDebt")]
        public decimal? ShortLongTermDebt { get; set; }

        [JsonPropertyName("shortTermDebt")]
        public decimal? ShortTermDebt { get; set; }

        [JsonPropertyName("shortTermInvestments")]
        public decimal? ShortTermInvestments { get; set; }

        [JsonPropertyName("temporaryEquityRedeemableNoncontrollingInterests")]
        public decimal? TemporaryEquityRedeemableNoncontrollingInterests { get; set; }

        [JsonPropertyName("totalAssets")]
        public decimal? TotalAssets { get; set; }

        [JsonPropertyName("totalCurrentAssets")]
        public decimal? TotalCurrentAssets { get; set; }

        [JsonPropertyName("totalCurrentLiabilities")]
        public decimal? TotalCurrentLiabilities { get; set; }

        [JsonPropertyName("totalLiab")]
        public decimal? TotalLiab { get; set; }

        [JsonPropertyName("totalPermanentEquity")]
        public decimal? TotalPermanentEquity { get; set; }

        [JsonPropertyName("totalStockholderEquity")]
        public decimal? TotalStockholderEquity { get; set; }

        [JsonPropertyName("treasuryStock")]
        public decimal? TreasuryStock { get; set; }

        [JsonPropertyName("warrants")]
        public decimal? Warrants { get; set; }
    }

    public partial class Highlights
    {
        [JsonPropertyName("MarketCapitalization")]
        public long MarketCapitalization { get; set; }

        [JsonPropertyName("MarketCapitalizationMln")]
        public string MarketCapitalizationMln { get; set; }

        [JsonPropertyName("EBITDA")]
        public long Ebitda { get; set; }

        [JsonPropertyName("PERatio")]
        public string PeRatio { get; set; }

        [JsonPropertyName("PEGRatio")]
        public decimal? PegRatio { get; set; }

        [JsonPropertyName("WallStreetTargetPrice")]
        public decimal? WallStreetTargetPrice { get; set; }

        [JsonPropertyName("BookValue")]
        public decimal? BookValue { get; set; }

        [JsonPropertyName("DividendShare")]
        public decimal? DividendShare { get; set; }

        [JsonPropertyName("DividendYield")]
        public decimal? DividendYield { get; set; }

        [JsonPropertyName("EarningsShare")]
        public decimal? EarningsShare { get; set; }

        [JsonPropertyName("EPSEstimateCurrentYear")]
        public decimal? EpsEstimateCurrentYear { get; set; }

        [JsonPropertyName("EPSEstimateNextYear")]
        public decimal? EpsEstimateNextYear { get; set; }

        [JsonPropertyName("EPSEstimateNextQuarter")]
        public string EpsEstimateNextQuarter { get; set; }

        [JsonPropertyName("EPSEstimateCurrentQuarter")]
        public decimal? EpsEstimateCurrentQuarter { get; set; }

        [JsonPropertyName("MostRecentQuarter")]
        public DateTimeOffset? MostRecentQuarter { get; set; }

        [JsonPropertyName("ProfitMargin")]
        public decimal? ProfitMargin { get; set; }

        [JsonPropertyName("OperatingMarginTTM")]
        public decimal? OperatingMarginTtm { get; set; }

        [JsonPropertyName("ReturnOnAssetsTTM")]
        public decimal? ReturnOnAssetsTtm { get; set; }

        [JsonPropertyName("ReturnOnEquityTTM")]
        public decimal? ReturnOnEquityTtm { get; set; }

        [JsonPropertyName("RevenueTTM")]
        public decimal? RevenueTtm { get; set; }

        [JsonPropertyName("RevenuePerShareTTM")]
        public decimal? RevenuePerShareTtm { get; set; }

        [JsonPropertyName("QuarterlyRevenueGrowthYOY")]
        public decimal? QuarterlyRevenueGrowthYoy { get; set; }

        [JsonPropertyName("GrossProfitTTM")]
        public decimal? GrossProfitTtm { get; set; }

        [JsonPropertyName("DilutedEpsTTM")]
        public decimal? DilutedEpsTtm { get; set; }

        [JsonPropertyName("QuarterlyEarningsGrowthYOY")]
        public decimal? QuarterlyEarningsGrowthYoy { get; set; }
    }

    public partial class OutstandingShares
    {
        [JsonPropertyName("annual")]
        public Dictionary<string, EarningAnnual> Annual { get; set; }

        [JsonPropertyName("quarterly")]
        public Dictionary<string, EarningAnnual> Quarterly { get; set; }
    }

    public partial class EarningAnnual
    {
        [JsonPropertyName("date")]
        public string Date { get; set; }

        [JsonPropertyName("sharesMln")]
        public string SharesMln { get; set; }
    }

    public partial class SharesStats
    {
        [JsonPropertyName("SharesOutstanding")]
        public decimal? SharesOutstanding { get; set; }

        [JsonPropertyName("SharesFloat")]
        public decimal? SharesFloat { get; set; }

        [JsonPropertyName("PercentInsiders")]
        public decimal? PercentInsiders { get; set; }

        [JsonPropertyName("PercentInstitutions")]
        public decimal? PercentInstitutions { get; set; }

        [JsonPropertyName("SharesShort")]
        public decimal? SharesShort { get; set; }

        [JsonPropertyName("SharesShortPriorMonth")]
        public decimal? SharesShortPriorMonth { get; set; }

        [JsonPropertyName("ShortRatio")]
        public decimal? ShortRatio { get; set; }

        [JsonPropertyName("ShortPercentOutstanding")]
        public decimal? ShortPercentOutstanding { get; set; }

        [JsonPropertyName("ShortPercentFloat")]
        public decimal? ShortPercentFloat { get; set; }
    }

    public partial class SplitsDividends
    {
        [JsonPropertyName("ForwardAnnualDividendRate")]
        public decimal? ForwardAnnualDividendRate { get; set; }

        [JsonPropertyName("ForwardAnnualDividendYield")]
        public decimal? ForwardAnnualDividendYield { get; set; }

        [JsonPropertyName("PayoutRatio")]
        public decimal? PayoutRatio { get; set; }

        [JsonPropertyName("DividendDate")]
        public DateTimeOffset? DividendDate { get; set; }

        [JsonPropertyName("ExDividendDate")]
        public DateTimeOffset? ExDividendDate { get; set; }

        [JsonPropertyName("LastSplitFactor")]
        public string LastSplitFactor { get; set; }

        [JsonPropertyName("LastSplitDate")]
        public DateTimeOffset? LastSplitDate { get; set; }

        [JsonPropertyName("NumberDividendsByYear")]
        public Dictionary<string, NumberDividendsByYear> NumberDividendsByYear { get; set; }
    }

    public partial class NumberDividendsByYear
    {
        [JsonPropertyName("Year")]
        public long Year { get; set; }

        [JsonPropertyName("Count")]
        public long Count { get; set; }
    }

    public partial class Valuation
    {
        [JsonPropertyName("TrailingPE")]
        public decimal? TrailingPe { get; set; }

        [JsonPropertyName("ForwardPE")]
        public decimal? ForwardPe { get; set; }

        [JsonPropertyName("PriceSalesTTM")]
        public decimal? PriceSalesTtm { get; set; }

        [JsonPropertyName("PriceBookMRQ")]
        public decimal? PriceBookMrq { get; set; }

        [JsonPropertyName("EnterpriseValueRevenue")]
        public decimal? EnterpriseValueRevenue { get; set; }

        [JsonPropertyName("EnterpriseValueEbitda")]
        public decimal? EnterpriseValueEbitda { get; set; }
    }

    public partial class FundamentalStock
    {
        public static FundamentalStock FromJson(string json)
        {
            json = json.Replace("\"0000-00-00\"", "null");
            return JsonConvert.DeserializeObject<FundamentalStock>(json, EODHistoricalData.NET.ConverterFundamentalStock.Settings);
        }
    }

    public static class SerializeFundamentalStock
    {
        public static string ToJson(this FundamentalStock self) => JsonConvert.SerializeObject(self, EODHistoricalData.NET.ConverterFundamentalStock.Settings);
    }

    internal static class ConverterFundamentalStock
    {
        public static List<string> Errors = new List<string>();
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal },
                new NullConverter(),
            },
            Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
            {
                Errors.Add(args.ErrorContext.Error.Message);
                args.ErrorContext.Handled = true;
            },
        };
    }
}
